export interface Article {
  pmid?: string;
  title: string;
  authors: string;
  journal: string;
  year: string;
  doi?: string;
  doiUrl?: string;
  studyType?: string;
  summary: string;
  forPatients: string;
  forPhysio: string;
  keyFindings: string[];
}

export interface ArticleIndexEntry {
  date: string;
  title: string;
  studyType?: string;
}

/** Generated by scripts/schedule-articles.mjs into public/articles/index.json. */
export interface ArticleIndex {
  generated: string;
  articles: ArticleIndexEntry[];
}

export interface DailyArticles {
  [categoryId: string]: Article;
}

export interface Category {
  id: string;
  label: string;
  full: string;
  color: string;
  mid: string;
  tag: string;
  tagText: string;
}

export interface Bookmark {
  article: Article;
  categoryId: string;
  savedAt: string;
}

export interface BookmarkStore {
  [key: string]: Bookmark;
}

export type AppView = 'research' | 'physle' | 'crossword' | 'saved' | 'about';

// Physle
export interface PhysleState {
  guesses: string[];
  current: string;
  done: boolean;
  won: boolean;
}

export interface PhysleStreak {
  count: number;
  lastDate: string;
  best: number;
}

export type LetterStatus = 'correct' | 'present' | 'absent' | 'empty' | 'tbd';

export interface LetterResult {
  letter: string;
  status: LetterStatus;
}

// Crossword
export interface CrosswordClue {
  answer: string;
  clue: string;
  startx: number;
  starty: number;
  orientation: 'across' | 'down';
  position: number;
}

export interface CrosswordData {
  rows: number;
  cols: number;
  result: CrosswordClue[];
}

export interface CrosswordIndexEntry {
  id: string;
  clues: number;
  rows: number;
  cols: number;
}

/** Generated by scripts/build-crosswords.mjs into public/crosswords/index.json. */
export interface CrosswordIndex {
  generated: string;
  puzzles: CrosswordIndexEntry[];
}

export interface CrosswordProgress {
  userLetters: { [key: string]: string };
  /** Legacy field from before solved clues were derived from the letters. */
  solvedClues?: number[];
  completedAt?: string;
}
